name: Update README Badges

on:
  workflow_run:
    workflows: ["Multi-Distribution Installation Testing"]
    types:
      - completed
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release info
        id: release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/Yahya-Zekry/internet-usage-monitor/releases/latest | jq -r '.tag_name // "v1.0.0"')
          echo "latest=${LATEST_RELEASE}" >> $GITHUB_OUTPUT
          echo "Latest release: ${LATEST_RELEASE}"

      - name: Get test status
        id: tests
        run: |
          # Get the latest workflow run status
          TEST_STATUS=$(curl -s https://api.github.com/repos/Yahya-Zekry/internet-usage-monitor/actions/workflows/test-installation.yml/runs | jq -r '.workflow_runs[0].conclusion // "unknown"')
          echo "status=${TEST_STATUS}" >> $GITHUB_OUTPUT
          echo "Test status: ${TEST_STATUS}"

      - name: Count supported distributions
        id: distros
        run: |
          # Count distributions from test matrix
          DISTRO_COUNT=$(grep -c "ubuntu:\|debian:\|fedora:\|archlinux:" .github/workflows/test-installation.yml || echo "7")
          echo "count=${DISTRO_COUNT}" >> $GITHUB_OUTPUT
          echo "Supported distributions: ${DISTRO_COUNT}"

      - name: Update badges in README
        run: |
          echo "Updating badges in README.md..."

          # Current badges in the README
          BADGES_SECTION='![License](https://img.shields.io/badge/license-MIT-blue.svg)
          ![Platform](https://img.shields.io/badge/platform-Linux-green.svg)
          ![Shell](https://img.shields.io/badge/shell-Bash-orange.svg)
          ![Conky](https://img.shields.io/badge/widget-Conky-purple.svg)'

          # Enhanced badges with dynamic values
          NEW_BADGES='![License](https://img.shields.io/badge/license-MIT-blue.svg)
          ![Platform](https://img.shields.io/badge/platform-Linux-green.svg)
          ![Shell](https://img.shields.io/badge/shell-Bash-orange.svg)
          ![Conky](https://img.shields.io/badge/widget-Conky-purple.svg)
          ![Release](https://img.shields.io/badge/release-${{ steps.release.outputs.latest }}-brightgreen.svg)
          ![Tests](https://img.shields.io/badge/tests-${{ steps.tests.outputs.status }}-${{ steps.tests.outputs.status == 'success' && 'brightgreen' || 'red' }}.svg)
          ![Distributions](https://img.shields.io/badge/distributions-${{ steps.distros.outputs.count }}%20tested-blue.svg)
          ![Yerba Mate](https://img.shields.io/badge/yerba%20mate-🧉%20balanced-green.svg)'

          echo "Badge update completed"

      - name: Commit badge updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "🏷️ Update README badges [skip ci]"
            git push
            echo "Badges updated and committed"
          else
            echo "No badge changes to commit"
          fi
